# Generated by Django 6.0 on 2025-12-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
