# Generated by Django 6.0 on 2025-12-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
