# Generated by Django 6.0 on 2025-12-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_alter_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
